import { SpecialTrait } from "../../interfaces/SpecialTrait";

export const _MortalMerits: SpecialTrait[] = [
  // ============= MENTAIS ============= //
  { 
    id: "investigative-aide", 
    name: "Assistente Investigativo", 
    labelKey: "merit.investigativeAide", 
    value: 1, 
    type: 'merit',
    fixed: true, 
    exclusive: true,
    customText: '',
    category: "Mental" 
  },
  { 
    id: "library", 
    name: "Biblioteca", 
    labelKey: "merit.library", 
    value: 1, 
    type: 'merit',
    min: 1, 
    max: 3, 
    fixed: false,
    category: "Mental" 
  },
  { 
    id: "good-time-management", 
    name: "Boa Gestão do Tempo", 
    labelKey: "merit.goodTimeManagement", 
    value: 3, 
    type: 'merit',
    fixed: true, 
    exclusive: true,
    category: "Mental" 
  },
  { 
    id: "common-sense", 
    name: "Bom Senso", 
    labelKey: "merit.commonSense", 
    value: 2, 
    type: 'merit',
    fixed: true, 
    exclusive: true, 
    category: "Mental" 
  },
  { 
    id: "encyclopedic-knowledge", 
    name: "Conhecimento Enciclopédico", 
    labelKey: "merit.encyclopedicKnowledge", 
    value: 2, 
    type: 'merit',
    fixed: true, 
    exclusive: true,
    customText: '',
    category: "Mental" 
  },
  { 
    id: "vice-ridden", 
    name: "Consumido por Vícios", 
    labelKey: "merit.viceRidden", 
    value: 2, 
    type: 'merit',
    fixed: true, 
    exclusive: true,
    category: "Mental" 
  },
  { 
    id: "holistic-awareness", 
    name: "Consciência Holística", 
    labelKey: "merit.holisticAwareness", 
    value: 1, 
    type: 'merit',
    fixed: true, 
    exclusive: true,
    category: "Mental" 
  },
  { 
    id: "interdisciplinary-specialty", 
    name: "Especialista Multidisciplinar", 
    labelKey: "merit.interdisciplinarySpecialty", 
    value: 1, 
    type: 'merit',
    fixed: true, 
    exclusive: true,
    category: "Mental" 
  },
  { 
    id: "professional-training", 
    name: "Formação Profissional", 
    labelKey: "merit.professionalTraining", 
    value: 1, 
    type: 'merit',
    min: 1, 
    max: 5, 
    fixed: false,
    customText: '',
    category: "Mental" 
  },
  { 
    id: "language", 
    name: "Idioma", 
    labelKey: "merit.language", 
    value: 1, 
    type: 'merit',
    fixed: true, 
    exclusive: false,
    customText: '',
    category: "Mental" 
  },
  { 
    id: "indomitable", 
    name: "Indomável", 
    labelKey: "merit.indomitable", 
    value: 3, 
    type: 'merit',
    fixed: true, 
    exclusive: true,
    category: "Mental" 
  },
  { 
    id: "eidetic-memory", 
    name: "Memória Eidética", 
    labelKey: "merit.eideticMemory", 
    value: 2, 
    type: 'merit',
    fixed: true, 
    exclusive: true,
    category: "Mental" 
  },
  { 
    id: "meditative-mind", 
    name: "Mente Meditativa", 
    labelKey: "merit.meditativeMind", 
    value: 1, 
    type: 'merit',
    min: 1, 
    max: 4, 
    fixed: false,
    category: "Mental" 
  },
  { 
    id: "trained-observer", 
    name: "Observador Treinado", 
    labelKey: "merit.trainedObserver", 
    value: 1, 
    type: 'merit',
    min: 1, 
    max: 3, 
    fixed: false,
    category: "Mental" 
  },
  { 
    id: "eye-for-the-strange", 
    name: "Olho para o Estranho", 
    labelKey: "merit.eyeForTheStrange", 
    value: 2, 
    type: 'merit',
    fixed: true, 
    exclusive: true,
    category: "Mental" 
  },
  { 
    id: "patient", 
    name: "Paciente", 
    labelKey: "merit.patient", 
    value: 1, 
    type: 'merit',
    fixed: true, 
    exclusive: true,
    category: "Mental" 
  },
  { 
    id: "area-of-expertise", 
    name: "Perito", 
    labelKey: "merit.areaOfExpertise", 
    value: 1, 
    type: 'merit',
    fixed: true, 
    exclusive: true,
    category: "Mental" 
  },
  { 
    id: "multilingual", 
    name: "Poliglota", 
    labelKey: "merit.multilingual", 
    value: 1, 
    type: 'merit',
    fixed: true, 
    exclusive: false,
    customText: '',
    category: "Mental" 
  },
  { 
    id: "investigative-prodigy", 
    name: "Prodígio Investigativo", 
    labelKey: "merit.investigativeProdigy", 
    value: 1, 
    type: 'merit',
    min: 1, 
    max: 5, 
    fixed: false,
    category: "Mental"
  },
  { 
    id: "fast-reflexes", 
    name: "Reflexos Rápidos", 
    labelKey: "merit.fastReflexes", 
    value: 1, 
    type: 'merit',
    min: 1, 
    max: 3, 
    fixed: false,
    category: "Mental"
  },
  { 
    id: "direction-sense", 
    name: "Senso de Direção",
    labelKey: "merit.directionSense", 
    value: 1, 
    type: 'merit',
    min: 1, 
    max: 1, 
    fixed: false,
    category: "Mental"
  },
  { 
    id: "danger-sense", 
    name: "Senso de Perigo",
    labelKey: "merit.dangerSense", 
    value: 2, 
    type: 'merit',
    min: 2, 
    max: 2, 
    fixed: false,
    category: "Mental"
  },
  { 
    id: "tolerance-for-biology", 
    name: "Tolerante à Biologia",
    labelKey: "merit.toleranceForBiology", 
    value: 2, 
    type: 'merit',
    min: 2, 
    max: 2, 
    fixed: false,
    category: "Mental"
  },
  { 
    id: "virtuous", 
    name: "Virtuoso",
    labelKey: "merit.virtuous", 
    value: 2, 
    type: 'merit',
    min: 2, 
    max: 2, 
    fixed: false,
    category: "Mental"
  },
  // ============= FÍSICAS ============= //
  {
    id: "crack-driver",
    name: "Ás do Volante",
    labelKey: "merit.crackDriver",
    value: 2,
    type: 'merit',
    min: 2,
    max: 3,
    fixed: false,
    exclusive: true,
    category: "Física"
  },
  {
    id: "ambidextrous",
    name: "Ambidestro",
    labelKey: "merit.ambidextrous",
    value: 3,
    type: 'merit',
    fixed: true,
    exclusive: true,
    category: "Física"
  },
  {
    id: "seizing-the-edge",
    name: "Aproveitar a Vantagem",
    labelKey: "merit.seizingTheEdge",
    value: 2,
    type: 'merit',
    fixed: true,
    exclusive: true,
    category: "Física"
  },
  {
    id: "demolisher",
    name: "Demolidor",
    labelKey: "merit.demolisher",
    value: 1,
    type: 'merit',
    min: 1,
    max: 3,
    fixed: false,
    exclusive: true,
    category: "Física"
  },
  {
    id: "double-jointed",
    name: "Flexibilidade nas Juntas",
    labelKey: "merit.doubleJointed",
    value: 2,
    type: 'merit',
    fixed: true,
    exclusive: true,
    category: "Física"
  },
  {
    id: "greyhound",
    name: "Galgo",
    labelKey: "merit.greyhound",
    value: 1,
    type: 'merit',
    fixed: true,
    exclusive: true,
    category: "Física"
  },
  {
    id: "giant",
    name: "Gigante",
    labelKey: "merit.giant",
    value: 3,
    type: 'merit',
    fixed: true,
    exclusive: true,
    category: "Física"
  },
  {
    id: "automotive-genius",
    name: "Gênio Automotivo",
    labelKey: "merit.automotiveGenius",
    value: 1,
    type: 'merit',
    fixed: true,
    exclusive: true,
    category: "Física"
  },
  {
    id: "relentless",
    name: "Implacável",
    labelKey: "merit.relentless",
    value: 2,
    type: 'merit',
    fixed: true,
    exclusive: true,
    category: "Física"
  },
  {
    id: "hardy",
    name: "Inquebrável",
    labelKey: "merit.hardy",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Física",
    min: 1,
    max: 3
  },
  {
    id: "fleet-of-foot",
    name: "Ligeiro",
    labelKey: "merit.fleetOfFoot",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Física",
    min: 1,
    max: 3
  },
  {
    id: "sleight-of-hand",
    name: "Mãos Leves",
    labelKey: "merit.sleightOfHand",
    value: 2,
    type: 'merit',
    fixed: true,
    exclusive: true,
    category: "Física"
  },
  {
    id: "parkour",
    name: "Parkour",
    labelKey: "merit.parkour",
    value: 1,
    type: 'merit',
    min: 1,
    max: 5,
    customText: '',
    fixed: false,
    exclusive: false,
    category: "Física",
  },
  {
    id: "small-framed",
    name: "Pequeno",
    labelKey: "merit.smallFramed",
    value: 2,
    type: 'merit',
    fixed: true,
    exclusive: true,
    category: "Física"
  },
  {
    id: "stunt-driver",
    name: "Proeza Automotiva",
    labelKey: "merit.stuntDriver",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Física",
    min: 1,
    max: 4,
    customText: ''
  },
  {
    id: "iron-stamina",
    name: "Resistência Férrea",
    labelKey: "merit.ironStamina",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Física",
    min: 1,
    max: 3
  },
  {
    id: "quick-draw",
    name: "Saque Rápido",
    labelKey: "merit.quickDraw",
    value: 1,
    type: 'merit',
    fixed: true,
    exclusive: true,
    category: "Física",
    customText: 'Especialização em Armamento ou Armas de Fogo'
  },
  
  // ============= SOCIAIS ============= //
  {
    id: "allies",
    name: "Aliados",
    labelKey: "merit.allies",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    customText: "Ex: Maçons, Igreja Católica, Cartel do Crime",
    category: "Social",
  },
  {
    id: "true_friend",
    name: "Amigo Verdadeiro",
    labelKey: "merit.true_friend",
    value: 3,
    type: 'merit',
    fixed: true,
    exclusive: false,
    customText: '',
    category: "Social",
  },
  {
    id: "anonymity",
    name: "Anonimato",
    labelKey: "merit.anonymity",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Social",
  },
  {
    id: "striking_looks",
    name: "Aparência Surpreendente",
    labelKey: "merit.striking_looks",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    customText: '',
    category: "Social",
  },
  {
    id: "taste",
    name: "Bom Gosto",
    labelKey: "merit.taste",
    value: 1,
    type: 'merit',
    fixed: true,
    exclusive: true,
    customText: 'Especialização em Ofícios ou Expressão',
    category: "Social",
  },
  {
    id: "contacts",
    name: "Contato",
    labelKey: "merit.contacts",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    customText: "Ex: Blogueiros, Criminosos, Acadêmicos",
    category: "Social",
  },
  {
    id: "fast_talking",
    name: "Eloquência",
    labelKey: "merit.fast_talking",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Social",
  },
  {
    id: "staff",
    name: "Equipe",
    labelKey: "merit.staff",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    customText: '',
    category: "Social",
  },
  {
    id: "fame",
    name: "Fama",
    labelKey: "merit.fame",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Social",
  },
  { 
    id: "hobbyist-clique", 
    name: "Filiação", 
    labelKey: "merit.hobbyistClique", 
    value: 2, 
    type: 'merit',
    min: 2, 
    max: 2, 
    fixed: true, 
    exclusive: true,
    category: "Social" 
  },
  { 
    id: "untouchable", 
    name: "Intocável", 
    labelKey: "merit.untouchable", 
    value: 1, 
    type: 'merit',
    min: 1, 
    max: 1, 
    fixed: true, 
    exclusive: true,
    category: "Social" 
  },
  {
    id: "mystery_cult_initiation",
    name: "Iniciado em Culto",
    labelKey: "merit.mystery_cult_initiation",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    customText: "Detalhes do culto, doutrina e relíquia",
    category: "Social",
  },  
  {
    id: "alternate_identity",
    name: "Identidade Alternativa",
    labelKey: "merit.alternate_identity",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    customText: "Descrição da identidade",
    category: "Social",
  },
  {
    id: "mentor",
    name: "Mentor",
    labelKey: "merit.mentor",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: true,
    customText: "Detalhes do culto, doutrina e relíquia",
    category: "Social",
  },
  {
    id: "status",
    name: "Status",
    labelKey: "merit.status",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: true,
    customText: "Nome da organização ou grupo",
    category: "Social",
  },
  {
    id: "resources",
    name: "Recursos",
    labelKey: "merit.resources",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Social",
  },
  {
    id: "safe_place",
    name: "Local Seguro",
    labelKey: "merit.safe_place",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: true,
    customText: "Descrição do local seguro",
    category: "Social",
  },
  {
    id: "retainer",
    name: "Servidor",
    labelKey: "merit.retainer",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    customText: "Nome e função do servidor",
    category: "Social",
  },
  {
    id: "spin_doctor",
    name: "Marqueteiro",
    labelKey: "merit.spin_doctor",
    value: 1,
    type: 'merit',
    fixed: true,
    exclusive: true,
    category: "Social",
  },
  {
    id: "iron_will",
    name: "Vontade de Ferro",
    labelKey: "merit.iron_will",
    value: 2,
    type: 'merit',
    fixed: true,
    exclusive: true,
    category: "Social",
  },
  {
    id: "barfly",
    name: "Habitué",
    labelKey: "merit.barfly",
    value: 2,
    type: 'merit',
    min: 2,
    max: 2,
    fixed: true,
    exclusive: false,
    category: "Social",
  },
  {
    id: "fixer",
    name: "Negociante",
    labelKey: "merit.fixer",
    value: 2,
    type: 'merit',
    fixed: true,
    exclusive: false,
    category: "Social",
  },
  { 
    id: "pusher", 
    name: "Suborno ", 
    labelKey: "merit.pusher", 
    value: 1, 
    type: 'merit',
    max: 1,
    fixed: true, 
    exclusive: true,
    category: "Social" 
  },
  {
    id: "sympathetic",
    name: "Simpático",
    labelKey: "merit.sympathetic",
    value: 2,
    type: 'merit',
    fixed: true,
    exclusive: false,
    category: "Social",
  },
  {
    id: "table_turner",
    name: "Virar o Jogo",
    labelKey: "merit.table_turner",
    value: 1,
    type: 'merit',
    fixed: true,
    exclusive: true,
    category: "Social",
  },
  {
    id: "takes_one_to_know_one",
    name: "Um Conhece o Outro",
    labelKey: "merit.takes_one_to_know_one",
    value: 1,
    type: 'merit',
    fixed: true,
    exclusive: true,
    category: "Social",
  },
  {
    id: "small_unit_tactics",
    name: "Táticas Militares",
    labelKey: "merit.small_unit_tactics",
    value: 2,
    type: 'merit',
    fixed: true,
    exclusive: true,
    category: "Social",
  },
  {
    id: "closed_book",
    name: "Livro Fechado",
    labelKey: "merit.closed_book",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: true,
    category: "Social",
  },
  {
    id: "inspiring",
    name: "Fonte de Inspiração",
    labelKey: "merit.inspiring",
    value: 3,
    type: 'merit',
    fixed: true,
    exclusive: false,
    category: "Social",
  },
  
  // ========= ESTILOS DE LUTA ========= //
  {
    id: "grappling",
    name: "Aprisionamento",
    labelKey: "merit.grappling",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Marcial",
  },
  {
    id: "improvised_weaponry",
    name: "Armas Improvisadas",
    labelKey: "merit.improvised_weaponry",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Marcial",
  },
  {
    id: "light_weapons",
    name: "Armas Leves",
    labelKey: "merit.light_weapons",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Marcial",
  },
  {
    id: "heavy_weapons",
    name: "Armas Pesadas",
    labelKey: "merit.heavy_weapons",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Marcial",
  },
  {
    id: "martial_arts",
    name: "Artes Marciais",
    labelKey: "merit.martial_arts",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Marcial",
  },
  {
    id: "marksmanship",
    name: "Atirador",
    labelKey: "merit.marksmanship",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Marcial",
  },
  {
    id: "street_fighting",
    name: "Briga de Rua",
    labelKey: "merit.street_fighting",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Marcial",
  },
  {
    id: "close_quarters_combat",
    name: "Combate em Espaços Fechados",
    labelKey: "merit.close_quarters_combat",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Marcial",
  },
  {
    id: "defensive_combat",
    name: "Combate Defensivo",
    labelKey: "merit.defensive_combat",
    value: 1,
    type: 'merit',
    fixed: true,
    exclusive: false,
    customText: "Briga ou Armamento",
    category: "Marcial",
  },
  {
    id: "armed_defense",
    name: "Defesa Armada",
    labelKey: "merit.armed_defense",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Marcial",
  },
  {
    id: "unarmed_defense",
    name: "Defesa Desarmada",
    labelKey: "merit.unarmed_defense",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Marcial",
  },
  {
    id: "cheap_shot",
    name: "Golpe Baixo",
    labelKey: "merit.cheap_shot",
    value: 2,
    type: 'merit',
    min: 2,
    max: 2,
    fixed: true,
    exclusive: true,
    category: "Marcial",
  },
  {
    id: "fighting_fitness",
    name: "Luta Rápida",
    labelKey: "merit.fighting_fitness",
    value: 2,
    type: 'merit',
    min: 2,
    max: 2,
    fixed: true,
    exclusive: false,
    customText: "Especialização escolhida",
    category: "Marcial",
  },
  {
    id: "choke_hold",
    name: "Mata Leão",
    labelKey: "merit.choke_hold",
    value: 2,
    type: 'merit',
    fixed: true,
    exclusive: false,
    category: "Marcial",
  },
  {
    id: "shiv",
    name: "Navalha",
    labelKey: "merit.shiv",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Marcial",
  },
  {
    id: "iron_skin",
    name: "Pele de Aço",
    labelKey: "merit.iron_skin",
    value: 2,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Marcial",
  },
  {
    id: "firefight",
    name: "Pistoleiro",
    labelKey: "merit.firefight",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Marcial",
  },
  {
    id: "police_tactics",
    name: "Táticas Policiais",
    labelKey: "merit.police_tactics",
    value: 1,
    type: 'merit',
    fixed: false,
    exclusive: false,
    category: "Marcial",
  }  
];
