import { SpecialTrait } from "../../interfaces/SpecialTrait";

export const _WerewolfMerits: SpecialTrait[] = [
  {
    id: "anchored",
    name: "Ancorado",
    labelKey: "merit.anchored",
    value: 1,
    type: 'merit',
    max: 2,
    category: "werewolf",
    fixed: true,
    exclusive: true,
  },
  {
    id: "bloodOrBoneAffinity",
    name: "Afinidade Sanguínea ou Óssea",
    labelKey: "merit.bloodOrBoneAffinity",
    value: 2,
    type: 'merit',
    min: 2,
    category: "werewolf",
    fixed: true,
    exclusive: true,
    customText: '',
  },
  {
    id: "livingWeapon",
    name: "Armas Naturais Aprimoradas",
    labelKey: "merit.livingWeapon",
    value: 3,
    type: 'merit',
    min: 3,
    category: "werewolf",
    fixed: true,
    exclusive: false,
    customText: '',
  },
  {
    id: "moonKissed",
    name: "Beijado pela Lua",
    labelKey: "merit.moonKissed",
    value: 1,
    type: 'merit',
    category: "werewolf",
    fixed: true,
    exclusive: true,
    customText: '',
  },
  {
    id: "songInYourHeart",
    name: "Canção em seu Coração",
    labelKey: "merit.songInYourHeart",
    value: 3,
    type: 'merit',
    category: "werewolf",
    fixed: true,
    exclusive: true,
  },
  {
    id: "codeOfHonor",
    name: "Código de Honra",
    labelKey: "merit.codeOfHonor",
    value: 2,
    type: 'merit',
    max: 2,
    category: "werewolf",
    fixed: true,
    exclusive: true,
    customText: '',
  },
  {
    id: "selfControl",
    name: "Compostura",
    labelKey: "merit.selfControl",
    value: 2,
    type: 'merit',
    max: 2,
    category: "werewolf",
    fixed: true,
    exclusive: true,
  },
  {
    id: "stringsOfTheHeart",
    name: "Cordas do Coração",
    labelKey: "merit.stringsOfTheHeart",
    value: 2,
    type: 'merit',
    max: 2,
    category: "werewolf",
    fixed: true,
    exclusive: true,
  },
  {
    id: "fading",
    name: "Desvanecer",
    labelKey: "merit.fading",
    value: 3,
    type: 'merit',
    max: 3,
    category: "werewolf",
    fixed: true,
    exclusive: true,
  },
  {
    id: "weakestLink",
    name: "Elo Mais Fraco",
    labelKey: "merit.weakestLink",
    value: 2,
    type: 'merit',
    max: 2,
    category: "werewolf",
    fixed: true,
    exclusive: true,
  },
  {
    id: "embodimentFirstborn",
    name: "Encarnação do Primogênito",
    labelKey: "merit.embodimentFirstborn",
    value: 5,
    type: 'merit',
    min: 5,
    category: "werewolf",
    fixed: true,
    exclusive: true,
  },
  {
    id: "favoredForm",
    name: "Forma Favorita",
    labelKey: "merit.favoredForm",
    value: 1,
    type: 'merit',
    category: "werewolf",
    fixed: true,
    exclusive: true,
    customText: '',
  },
  {
    id: "fortifiedForm",
    name: "Forma Fortificada",
    labelKey: "merit.fortifiedForm",
    value: 3,
    type: 'merit',
    min: 3,
    category: "werewolf",
    fixed: true,
    exclusive: false,
    customText: '',
  },
  {
    id: "dedicatedLocus",
    name: "Locus Dedicado",
    labelKey: "merit.dedicatedLocus",
    value: 1,
    type: 'merit',
    category: "werewolf",
    fixed: true,
    exclusive: true,
    customText: '',
  },
  {
    id: "packDynamics",
    name: "Matilha Dinâmica",
    labelKey: "merit.packDynamics",
    value: 3,
    type: 'merit',
    min: 3,
    category: "werewolf",
    fixed: true,
    exclusive: true,
  },
  {
    id: "impartialMediator",
    name: "Mediador Imparcial",
    labelKey: "merit.impartialMediator",
    value: 3,
    type: 'merit',
    min: 3,
    max: 3,
    category: "werewolf",
    fixed: true,
    exclusive: true,
  },
  {
    id: "resonanceShaper",
    name: "Modelador de Ressonância",
    labelKey: "merit.resonanceShaper",
    value: 3,
    type: 'merit',
    min: 3,
    max: 3,
    category: "werewolf",
    fixed: true,
    exclusive: true,
  },
  {
    id: "nowhereToRun",
    name: "Nenhum Lugar Para Correr",
    labelKey: "merit.nowhereToRun",
    value: 2,
    type: 'merit',
    min: 2,
    max: 2,
    category: "werewolf",
    fixed: true,
    exclusive: true,
  },
  {
    id: "hearingWhispers",
    name: "Perceber as Fraquezas",
    labelKey: "merit.hearingWhispers",
    value: 2,
    type: 'merit',
    min: 2,
    max: 2,
    category: "werewolf",
    fixed: true,
    exclusive: true,
  },
  {
    id: "controlledBurn",
    name: "Queima Controlada",
    labelKey: "merit.controlledBurn",
    value: 2,
    type: 'merit',
    min: 2,
    max: 2,
    category: "werewolf",
    fixed: true,
    exclusive: true,
  },
  {
    id: "soundsOfTheCity",
    name: "Sons da Cidade",
    labelKey: "merit.soundsOfTheCity",
    value: 2,
    type: 'merit',
    min: 2,
    max: 2,
    category: "werewolf",
    fixed: true,
    exclusive: true,
  },
  {
    id: "creativeTactician",
    name: "Táticas Criativas",
    labelKey: "merit.creativeTactician",
    value: 3,
    type: 'merit',
    min: 3,
    max: 3,
    category: "werewolf",
    fixed: true,
    exclusive: true,
  },
  {
    id: "residentialTerritory",
    name: "Território Residencial",
    labelKey: "merit.residentialTerritory",
    value: 1,
    type: 'merit',
    category: "werewolf",
    fixed: true,
    exclusive: true,
  },
  {
    id: "totem",
    name: "Totem",
    labelKey: "merit.totem",
    value: 1,
    type: 'merit',
    category: "werewolf",
    fixed: true,
    exclusive: true,
  },

  // =========== MARCIAIS =========== //
  {
    id: 'efficient-killer',
    name: 'Assassino Eficiente',
    labelKey: "merit.efficient_killer",
    value: 2,
    type: 'merit',
    min: 2,
    max: 2,
    fixed: true,
    exclusive: true,
    category: 'werewolf_fighting',
  },
  {
    id: 'relentless-assault',
    name: 'Ataque Descuidado (Estilo)',
    labelKey: "merit.relentless_assault",
    value: 2,
    type: 'merit',
    min: 2,
    max: 2,
    fixed: true,
    exclusive: true,
    category: 'werewolf_fighting',
  },
  {
    id: 'flanking',
    name: 'Flanquear',
    labelKey: "merit.flanking",
    value: 2,
    type: 'merit',
    min: 2,
    max: 2,
    fixed: true,
    exclusive: true,
    category: 'werewolf_fighting',
  },
  {
    id: 'instinctive-defense',
    name: 'Defesa Instintiva',
    labelKey: "merit.instinctive_defense",
    value: 2,
    type: 'merit',
    min: 2,
    max: 2,
    fixed: true,
    exclusive: true,
    category: 'werewolf_fighting',
  },
  {
    id: 'call-out',
    name: 'Desafiar',
    labelKey: "merit.call_out",
    value: 2,
    type: 'merit',
    min: 2,
    max: 2,
    fixed: true,
    exclusive: true,
    category: 'werewolf_fighting',
  },
  {
    id: 'spiritual-blockage',
    name: 'Bloqueio de Essência',
    labelKey: "merit.spiritual_blockage",
    value: 2,
    type: 'merit',
    min: 2,
    max: 2,
    fixed: true,
    exclusive: true,
    category: 'werewolf_fighting',
  },
  {
    id: 'tactical-shifting',
    name: 'Mudança Tática',
    labelKey: "merit.tactical_shifting",
    value: 1,
    type: 'merit',
    fixed: true,
    exclusive: true,
    category: 'werewolf_fighting',
  },
  {
    id: 'warcry',
    name: 'Grito de Guerra',
    labelKey: "merit.warcry",
    value: 2,
    type: 'merit',
    min: 2,
    max: 2,
    fixed: true,
    exclusive: true,
    category: 'werewolf_fighting',
  },
];