import { SpecialTrait } from "../../interfaces/SpecialTrait";

export const moonGifts: SpecialTrait[] = [
  {
    id: "crescent-moon",
    name: "Dom da Lua Crescente",
    labelKey: "gift.crescent_moon",
    value: 1,
    max: 5,
    type: 'gift',
    category: "moon_gift",
    fixed: false,
    exclusive: true,
  },
  {
    id: "full-moon",
    name: "Dom da Lua Cheia",
    labelKey: "gift.full_moon",
    value: 1,
    max: 5,
    type: 'gift',
    category: "moon_gift",
    fixed: false,
    exclusive: true,
  },
  {
    id: "gibbous-moon",
    name: "Dom da Lua Gibosa",
    labelKey: "gift.gibbous_moon",
    value: 1,
    max: 5,
    type: 'gift',
    category: "moon_gift",
    fixed: false,
    exclusive: true,
  },
  {
    id: "half-moon",
    name: "Dom da Meia-Lua",
    labelKey: "gift.half_moon",
    value: 1,
    max: 5,
    type: 'gift',
    category: "moon_gift",
    fixed: false,
    exclusive: true,
  },
  {
    id: "new-moon",
    name: "Dom da Lua Nova",
    labelKey: "gift.new_moon",
    value: 1,
    max: 5,
    type: 'gift',
    category: "moon_gift",
    fixed: false,
    exclusive: true,
  },
];